//! Module for the lexer and parser for `MathExp`
//! WARNING: this file has been generated by
//! Hime Parser Generator 4.3.0

use hime_redist::ast::{AstImpl, AstNode};
use hime_redist::errors::ParseErrors;
use hime_redist::lexers::automaton::Automaton;
use hime_redist::lexers::impls::ContextFreeLexer;
use hime_redist::lexers::Lexer;
use hime_redist::parsers::lrk::LRkAutomaton;
use hime_redist::parsers::lrk::LRkParser;
use hime_redist::parsers::Parser;
use hime_redist::result::{ParseResult, ParseResultAst};
use hime_redist::symbols::SemanticBody;
use hime_redist::symbols::SemanticElementTrait;
use hime_redist::symbols::Symbol;
use hime_redist::text::Text;
use hime_redist::tokens::TokenRepository;

/// Static resource for the serialized lexer automaton
static LEXER_AUTOMATON: &[u8] = include_bytes!("math_exp_lexer.bin");

/// The unique identifier for terminal `SEPARATOR`
pub const ID_TERMINAL_SEPARATOR: u32 = 0x0004;
/// The unique identifier for terminal `NUMBER`
pub const ID_TERMINAL_NUMBER: u32 = 0x0007;

/// The unique identifier for the default context
pub const CONTEXT_DEFAULT: u16 = 0;

/// The collection of terminals matched by this lexer
/// The terminals are in an order consistent with the automaton,
/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
pub const TERMINALS: &[Symbol] = &[
    Symbol {
        id: 0x0001,
        name: "ε"
    },
    Symbol {
        id: 0x0002,
        name: "$"
    },
    Symbol {
        id: 0x0004,
        name: "SEPARATOR"
    },
    Symbol {
        id: 0x0007,
        name: "NUMBER"
    },
    Symbol {
        id: 0x000D,
        name: "("
    },
    Symbol {
        id: 0x000E,
        name: ")"
    },
    Symbol {
        id: 0x000F,
        name: "*"
    },
    Symbol {
        id: 0x0011,
        name: "/"
    },
    Symbol {
        id: 0x0013,
        name: "+"
    },
    Symbol {
        id: 0x0015,
        name: "-"
    }
];

/// Creates a new lexer
fn new_lexer<'a: 'b, 'b, 'c>(
    repository: TokenRepository<'a, 'b, 'c>,
    errors: &'c mut ParseErrors<'a>
) -> Lexer<'a, 'b, 'c> {
    let automaton = Automaton::new(LEXER_AUTOMATON);
    Lexer::ContextFree(ContextFreeLexer::new(repository, errors, automaton, 0x0004))
}

/// Static resource for the serialized parser automaton
static PARSER_AUTOMATON: &[u8] = include_bytes!("math_exp_parser.bin");

/// The unique identifier for variable `exp_atom`
pub const ID_VARIABLE_EXP_ATOM: u32 = 0x0008;
/// The unique identifier for variable `exp_factor`
pub const ID_VARIABLE_EXP_FACTOR: u32 = 0x0009;
/// The unique identifier for variable `exp_term`
pub const ID_VARIABLE_EXP_TERM: u32 = 0x000A;
/// The unique identifier for variable `exp`
pub const ID_VARIABLE_EXP: u32 = 0x000B;


/// The collection of variables matched by this parser
/// The variables are in an order consistent with the automaton,
/// so that variable indices in the automaton can be used to retrieve the variables in this table
pub const VARIABLES: &[Symbol] = &[
    Symbol {
        id: 0x0008,
        name: "exp_atom"
    },
    Symbol {
        id: 0x0009,
        name: "exp_factor"
    },
    Symbol {
        id: 0x000A,
        name: "exp_term"
    },
    Symbol {
        id: 0x000B,
        name: "exp"
    },
    Symbol {
        id: 0x0017,
        name: "__VAxiom"
    }
];

/// The collection of virtuals matched by this parser
/// The virtuals are in an order consistent with the automaton,
/// so that virtual indices in the automaton can be used to retrieve the virtuals in this table
pub const VIRTUALS: &[Symbol] = &[

];

/// Represents a set of semantic actions in this parser
#[allow(unused_variables)]
pub trait Actions {
    /// The OnNumber semantic action
    fn on_number(&mut self, head: Symbol, body: &dyn SemanticBody) {}
    /// The OnMult semantic action
    fn on_mult(&mut self, head: Symbol, body: &dyn SemanticBody) {}
    /// The OnDiv semantic action
    fn on_div(&mut self, head: Symbol, body: &dyn SemanticBody) {}
    /// The OnPlus semantic action
    fn on_plus(&mut self, head: Symbol, body: &dyn SemanticBody) {}
    /// The OnMinus semantic action
    fn on_minus(&mut self, head: Symbol, body: &dyn SemanticBody) {}
}

/// The structure that implements no action
pub struct NoActions {}

impl Actions for NoActions {}

/// Parses the specified string with this parser
#[must_use]
pub fn parse_str(input: &str) -> ParseResult<'static, '_, 'static, AstImpl> {
    let text = Text::from_str(input);
    parse_text(text, &mut NoActions {})
}

/// Parses the specified string with this parser
pub fn parse_str_with<'t>(input: &'t str, actions: &mut dyn Actions) -> ParseResult<'static, 't, 'static, AstImpl> {
    let text = Text::from_str(input);
    parse_text(text, actions)
}

/// Parses the specified string with this parser
#[must_use]
pub fn parse_string(input: String) -> ParseResultAst {
    let text = Text::from_string(input);
    parse_text(text, &mut NoActions {})
}

/// Parses the specified string with this parser
pub fn parse_string_with(input: String, actions: &mut dyn Actions) -> ParseResultAst {
    let text = Text::from_string(input);
    parse_text(text, actions)
}

/// Parses the specified stream of UTF-8 with this parser
///
/// # Errors
///
/// Return an `std::io::Error` when reading the stream as UTF-8 fails
pub fn parse_utf8_stream(input: &mut dyn std::io::Read) -> Result<ParseResultAst, std::io::Error> {
    let text = Text::from_utf8_stream(input)?;
    Ok(parse_text(text, &mut NoActions {}))
}

pub fn parse_utf8_stream_with(input: &mut dyn std::io::Read, actions: &mut dyn Actions) -> ParseResultAst {
    let text = Text::from_utf8_stream(input).unwrap();
    Ok(parse_text(text, actions))
}

/// Parses the specified text with this parser
fn parse_text<'t>(text: Text<'t>, actions: &mut dyn Actions) -> ParseResult<'static, 't, 'static, AstImpl> {
    parse_text_with(text, TERMINALS, VARIABLES, VIRTUALS, actions)
}

/// Parses the specified text with this parser
fn parse_text_with<'s, 't, 'a>(
    text: Text<'t>,
    terminals: &'a [Symbol<'s>],
    variables: &'a [Symbol<'s>],
    virtuals: &'a [Symbol<'s>],
    actions: &mut dyn Actions
) -> ParseResult<'s, 't, 'a, AstImpl> {
    let mut my_actions = |index: usize, head: Symbol, body: &dyn SemanticBody| match index {
        0 => actions.on_number(head, body),
        1 => actions.on_mult(head, body),
        2 => actions.on_div(head, body),
        3 => actions.on_plus(head, body),
        4 => actions.on_minus(head, body),
        _ => ()
    };

    let mut result = ParseResult::<AstImpl>::new(terminals, variables, virtuals, text);
    {
        let data = result.get_parsing_data();
        let mut lexer = new_lexer(data.0, data.1);
        let automaton = LRkAutomaton::new(PARSER_AUTOMATON);
        let mut parser = LRkParser::new(&mut lexer, variables, virtuals, automaton, data.2, &mut my_actions);
        parser.parse();
    }
    result
}

/// Visitor interface
#[allow(unused_variables)]
pub trait Visitor {
    fn on_terminal_separator(&self, node: &AstNode) {}
    fn on_terminal_number(&self, node: &AstNode) {}
    fn on_variable_exp_atom(&self, node: &AstNode) {}
    fn on_variable_exp_factor(&self, node: &AstNode) {}
    fn on_variable_exp_term(&self, node: &AstNode) {}
    fn on_variable_exp(&self, node: &AstNode) {}
}

/// Walk the AST of a result using a visitor
pub fn visit(result: &ParseResult<AstImpl>, visitor: &dyn Visitor) {
    let ast = result.get_ast();
    let root = ast.get_root();
    visit_ast_node(root, visitor);
}

/// Walk the sub-AST from the specified node using a visitor
pub fn visit_ast_node(node: AstNode, visitor: &dyn Visitor) {
    let children = node.children();
    for child in children.iter() {
        visit_ast_node(child, visitor);
    }
    match node.get_symbol().id {
        0x0004 => visitor.on_terminal_separator(&node),
        0x0007 => visitor.on_terminal_number(&node),
        0x0008 => visitor.on_variable_exp_atom(&node),
        0x0009 => visitor.on_variable_exp_factor(&node),
        0x000A => visitor.on_variable_exp_term(&node),
        0x000B => visitor.on_variable_exp(&node),
        _ => ()
    };
}
